name: Build & Test

on:
  push:
    branches: 
      - master
      - 'feature/**'
#  pull_request:
#    branches: [ master ]

env:
  configuration: Release
  artifacts-dir: nupkgs

jobs:
 
  build:

    runs-on: windows-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
      with:
       fetch-depth: 0
    
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.9
      with:
        versionSpec: '5.x'
    
    - name: Use GitVersion
      id: gitversion # step id used as reference for output values
      uses: gittools/actions/gitversion/execute@v0.9.9
      run: |
        echo "PreReleaseTag: ${{ steps.gitversion.outputs.preReleaseTag }}"
        echo "PreReleaseNumber: ${{ steps.gitversion.outputs.preReleaseNumber }}"
        echo "BuildMetaData: ${{ steps.gitversion.outputs.buildMetaData }}"
        echo "SemVer: ${{ steps.gitversion.outputs.semVer }}"
        echo "AssemblySemVer: ${{ steps.gitversion.outputs.assemblySemVer }}"
        echo "AssemblySemFileVer: ${{ steps.gitversion.outputs.assemblySemFileVer }}"
        echo "FullSemVer: ${{ steps.gitversion.outputs.fullSemVer }}"
        echo "CommitsSinceVersionSource: ${{ steps.gitversion.outputs.commitsSinceVersionSource }}"
        echo "CommitsSinceVersionSourcePadded: ${{ steps.gitversion.outputs.commitsSinceVersionSourcePadded }}"
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
     #restore build and test as one command in order to not copy/paste the same arguments      
    - name: Restore, build, and run tests
      run: dotnet test -c ${{env.configuration}} -p:AssemblyVersion=${{ steps.gitversion.outputs.assemblySemVer }} -p:FileVersion=${{ steps.gitversion.outputs.assemblySemFileVer }} -p:InformationalVersion=${{ steps.gitversion.outputs.informationalVersion }}
      
    - name: Pack
      run: dotnet pack --no-build -c ${{env.configuration}} -o:${{env.artifacts-dir}}  -p:PackageVersion=${{ steps.gitversion.outputs.majorMinorPatch }}

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.2
      with:
        name: Nuget
        path: ${{env.artifacts-dir}}/*.nupkg
        retention-days: 3