name: Build & Test

on:
  push:
    branches: 
      - master
      - 'feature/**'
#  pull_request:
#    branches: [ master ]

env:
  configuration: Release
  artifacts-dir: nupkgs

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
      with:
       fetch-depth: 0
    
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.9
      with:
        versionSpec: '5.x'
    
    - name: Use GitVersion
      id: gitversion # step id used as reference for output values
      uses: gittools/actions/gitversion/execute@v0.9.9
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    # Restore build and test as one command in order to not copy/paste the same arguments      
    - name: Restore, build, and run tests
      run: dotnet test -c ${{env.configuration}} -p:AssemblyVersion=${{ steps.gitversion.outputs.assemblySemVer }} -p:FileVersion=${{ steps.gitversion.outputs.assemblySemFileVer }} -p:InformationalVersion=${{ steps.gitversion.outputs.informationalVersion }}
      
    # Place nuget packages into env.artifacts-dir directory
    - name: Pack
      run: dotnet pack --no-build -c ${{env.configuration}} -o:${{env.artifacts-dir}}  -p:PackageVersion=${{ steps.gitversion.outputs.nuGetVersionV2 }}
    
    - name: Store Version
      uses: jsdaniell/create-json@1.1.2
      with:
       name: artifact.json
       json: |
         {
           "assembly-version": ${{ steps.gitversion.outputs.assemblySemVer }}, 
           "assembly-file-version": ${{ steps.gitversion.outputs.assemblySemFileVer }}, 
           "nuget-version": ${{ steps.gitversion.outputs.nuGetVersionV2 }}, 
         }
       dir: ${{env.artifacts-dir}}
     
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2.2.2
      with:
        name: Artifacts
        path: ${{env.artifacts-dir}}/
        retention-days: 3
        
    