name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Unzip strong name snk
      uses: montudor/action-zip@v0.1.0
      with:
        args: unzip -P ${{ secrets.strong_snk }} ./tools/strong_name/binstate.snk.zip -d ./private
    - name: Setup .net core 2.2
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.207
    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Setup side by side .NET SDKs on Windows
      if: matrix.os == 'windows-latest'
      run: |
        SET DOTNET_21_ROOT=%DOTNET_ROOT:3.1.101=2.2.207%
        xcopy /s /y /d %DOTNET_31_ROOT% %DOTNET_ROOT%
      shell: cmd
    - name: Setup side by side .NET SDKs on *nix
      if: matrix.os != 'windows-latest'
      run: |
        rsync -a ${DOTNET_ROOT/3.1.101/2.2.207}/* $DOTNET_ROOT/
    - name: Install dependencies
      working-directory: src
      run: dotnet restore
    - name: Build
      working-directory: src
      run: dotnet build --configuration Release --no-restore -p:CoreOnly=True
    - name: Test
      working-directory: src
      run: dotnet test --no-restore --verbosity normal --framework netcoreapp2.2 --framework netcoreapp3.1
