name: Publish nugets

on: workflow_dispatch

env:
 artifacts-dir: nupkgs

jobs:
 
  publish:
    runs-on: ubuntu-latest 
    
    steps:
       # https://github.com/dawidd6/action-download-artifact
    - name: Download artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        workflow: build-and-test.yml         # Required, workflow file name or ID
        branch: master
        name: Artifacts
        
    - name: Read version
      id: version
      uses: antifree/json-to-variables@v1.0.1
      with:
        filename: artifact.json
        prefix: ''
        
    - run: echo ${{steps.version.outputs.assembly-version}}
     
        
#    - name: Publish
#       run: dotnet nuget push "${{env.artifacts-dir}}/*.nupkg" -k ${{secrets.nuget_api_key}} -s https://api.nuget.org/v3/index.json 