name: Publish nugets

on: workflow_dispatch

env:
 artifacts-dir: nupkgs

jobs:
 
  publish:
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v2.0.8
        with:
        path: ${{env.artifacts-dir}}/*.nupkg

    - name: Publish
      run: dotnet nuget push "${{env.artifacts-dir}}/*.nupkg" -k ${{secrets.nuget_api_key}}