name: Publish nugets

on: workflow_dispatch

env:
 artifacts-dir: nupkgs

jobs:
 
  publish:
    runs-on: ubuntu-latest 
    
    steps:
       # https://github.com/dawidd6/action-download-artifact
    - name: Download artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        workflow: build-and-test.yml         # Required, workflow file name or ID
        branch: master
        # pr: ${{github.event.pull_request.number}} # Optional, will get head commit SHA
        
        # Optional, uploaded artifact name,
        # will download all artifacts if not specified
        # and extract them in respective subdirectories
        # https://github.com/actions/download-artifact#download-all-artifacts
        name: Nuget
        path: ${{env.artifacts-dir}}
        
    - name: Publish
      run: dotnet nuget push "${{env.artifacts-dir}}/*.nupkg" -k ${{secrets.nuget_api_key}}