name: Release to Market

on: workflow_dispatch

env:
  nugets-dir: nupkgs

jobs:

  publish:
    runs-on: ubuntu-latest

    steps:
      # https://github.com/dawidd6/action-download-artifact
      -
        name: Download artifact
        uses: dawidd6/action-download-artifact@v9
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow:     build-and-test.yml         # Required, workflow file name or ID
          branch:       ${{ github.ref_name }}
          name:         Artifacts

      -
        name: Read version
        id:   version
        uses: antifree/json-to-variables@v1.0.1
        with:
          filename: version.json

      -
        name: Publish Nugets to nuget.org
        run: |
          for file in nupkgs/*.nupkg; do
            echo "$file"
            dotnet nuget push "$file" -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_API_KEY }}
          done
        shell: bash

      -
        name: Make Github Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name:                v${{ env.json_nuget-version }}
          files:                   ${{ env.nugets-dir }}/*.nupkg
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
